name: Development environment

on:
  workflow_dispatch:
    inputs:
      power:
        description: "Power"
        required: true
        type: choice
        options:
          - true
          - false

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/checkout@v2
      - name: Extract secrets
        env:
          GOOGLE_ENVIRONMENT_TARGET: development
          GOOGLE_POWER: ${{ github.event.inputs.power }}
          TF_GOOGLE_CREDENTIAL_FILE: ${{ secrets.TF_GOOGLE_CREDENTIAL_FILE }}
          TF_ROOT_CRT_FILE: ${{ secrets.TF_ROOT_CRT_FILE }}
          TF_ROOT_KEY_FILE: ${{ secrets.TF_ROOT_KEY_FILE }}
          TF_TERRAFORM_TFVARS: ${{ secrets.TF_TERRAFORM_TFVARS }}
        run: ./scripts/extract-secrets.sh
      - name: Reverse terraform
        run: ./scripts/reverse-terraform.sh
      - name: Terraform
        run: |
          cd root/ && \
          terraform plan | sed --regexp-extended 's/value: \"[^\"]+\"/value: \"****\"/g'
      - name: Print outputs
        run: |
          [ ${{ github.event.inputs.power }} = true ] && echo '::notice::サーバーは起動状態です' || echo '::notice::サーバーは停止状態です'
