name: Health check

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --head https://p-at.net/index.txt && \
          curl --head http://insecure.p-at.net/index.txt
