name: "[Schedule] Keep"

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        git config --local user.email "git.invalid"
        git config --local user.name "git"
        git switch --create "_keep"
        git commit --amend --message "_keep"
        git push --force-with-lease origin _keep
