name: "[Schedule] Restart"
on:
  schedule:
    # UTC
    - cron: "0 21 * * *"

jobs:
  check_channels:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
      - uses: actions/checkout@v2
      - name: Check number of channels
        id: num_channels
        run: echo "::set-output name=value::$(scripts/num-channels.ts)"
      - name: Warn if some channels are broadcasting
        if: steps.num_channels.outputs.value > 0
        run: echo '::warning::${{ steps.num_channels.outputs.value }} チャンネルが配信中のため再起動を中止しました。'
    outputs:
      num_channels: ${{ steps.num_channels.outputs.value }}
  restart:
    needs: check_channels
    if: needs.check_channels.outputs.num_channels == 0
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/checkout@v2
      - name: Extract secrets
        env:
          GOOGLE_ENVIRONMENT_TARGET: production
          GOOGLE_POWER: true
          LOGFLARE_URI: /logs/json?api_key=${{ secrets.LOGFLARE_API_KEY }}&source=c565ddc7-1d34-4fd2-9e68-0b6339577dfa
          TF_GOOGLE_CREDENTIAL_FILE: ${{ secrets.TF_GOOGLE_CREDENTIAL_FILE }}
          TF_ROOT_CRT_FILE: ${{ secrets.TF_ROOT_CRT_FILE }}
          TF_ROOT_KEY_FILE: ${{ secrets.TF_ROOT_KEY_FILE }}
          TF_TERRAFORM_TFVARS: ${{ secrets.TF_TERRAFORM_TFVARS }}
        run: ./scripts/extract-secrets.sh
      - name: Reverse terraform
        run: ./scripts/reverse-terraform.sh
      - name: Terraform
        run: |
          cd root/ && \
          terraform taint google_compute_instance.tf_cloud_01 && \
          terraform apply -auto-approve | sed --regexp-extended 's/value: \"[^\"]+\"/value: \"****\"/g'
